# Generated by Django 6.1 on 2026-08-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeCXUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threecx_id', models.IntegerField(unique=True)),
                ('extension', models.CharField(max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_registered', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('primary_group_id', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
