# Generated by Django 6.1 on 2026-08-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_phonebookaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookxml',
            name='xml_file',
            field=models.FileField(blank=True, help_text='Only needed for manufacturers without a dynamic generator (see phonebook.generators). Fanvil is generated live from PostgreSQL and does not need a file uploaded here.', null=True, upload_to='phonebooks/'),
        ),
    ]
